# Generated by Django 4.1.7 on 2023-03-21 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_complaints_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='step',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=255),
        ),
    ]
