# Generated by Django 4.1.7 on 2023-03-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_complaints_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
