# Generated by Django 4.1.7 on 2023-03-22 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_complaints_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='passport_date_issued',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='complaints',
            name='passport_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
