# Generated by Django 4.1.7 on 2023-03-24 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_complaints_passport_date_issued_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='passport_back',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='complaints',
            name='passport_front',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
