# Generated by Django 4.1.7 on 2023-03-28 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_queing_mydocs'),
    ]

    operations = [
        migrations.AddField(
            model_name='queing',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
