# Generated by Django 4.1.7 on 2023-03-28 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_queing_completed'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyDocs',
            new_name='ComplaintDocs',
        ),
    ]
