# Generated by Django 4.1.7 on 2023-03-28 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_complaintdocs_id_alter_queing_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Queing',
            new_name='ComplaintsQueing',
        ),
    ]
