# Generated by Django 4.1.7 on 2023-03-28 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_rename_queing_complaintsqueing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaintsqueing',
            name='step',
        ),
        migrations.AddField(
            model_name='complaints',
            name='passport_birthdate',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='complaints',
            name='passport_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
