# Generated by Django 4.1.7 on 2023-03-29 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_remove_complaintsqueing_step_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='docs_url',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
