# Generated by Django 4.1.7 on 2023-03-29 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_complaints_docs_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='docs_url',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='passport_back',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='passport_birthdate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='passport_date_issued',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='passport_front',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='passport_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='passport_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
