# Generated by Django 4.1.7 on 2023-03-29 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_alter_complaints_docs_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='step',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=255),
        ),
        migrations.DeleteModel(
            name='ComplaintsQueing',
        ),
    ]
