# Generated by Django 4.1.7 on 2023-03-30 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_alter_complaints_step_delete_complaintsqueing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authentication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, null=True)),
                ('twillio_sid', models.CharField(max_length=255, null=True)),
                ('twillio_token', models.CharField(max_length=255, null=True)),
                ('ocr_license_code', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
