# Generated by Django 4.1.7 on 2023-03-31 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_authentication'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='confirmation_token',
            field=models.TextField(null=True),
        ),
    ]
