# Generated by Django 4.1.7 on 2023-03-31 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_complaints_confirmation_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaints',
            name='confirmation_token',
        ),
        migrations.AddField(
            model_name='complaints',
            name='confirm',
            field=models.BooleanField(default=False),
        ),
    ]
